<?PHP

$gammes = array(
	'classique' => "Tirage Classique",
	'poster' => "Poster",
	'art' => "Tirage 'Fine Art'",
	'toile' => "Photographie sur toile",
	'dibond' => "Photographie sur 'Dibond'",
	'encadrement' => "Impression haute qualité avec encadrement 'Caisse Américaine'",
);

$formats = array(
	'10x15' => "10x15",
	'13x19' => "13x19",
	'15x15' => "15x15",
	'15x21' => "15x21",
	'20x20' => "20x20",
	'20x30' => "20x30",
	'30x30' => "30x30",
	'30x45' => "30x45",
	'40x60' => "40x60",
	'50x75' => "50x75",
	'60x90' => "60x90",
);

$delais = array(
	1 => "24 heures",
	2 => "48 heures",
	7 => "1 semaine",
	14 => "2 semaines",
);

//
$i = 0;
$tirages = array(
	array(
		'id' => $i++,
		'code' => '10x15',
		'libelle' => "Tirage Classique 10x15cm",
		'format' => '10x15',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 3,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '10x15-c',
		'libelle' => "Tirage Classique 10x15cm avec cartonnage",
		'format' => '10x15',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 4,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '13x19',
		'libelle' => "Tirage Classique 13x19cm",
		'format' => '13x19',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 5,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '13x19-c',
		'libelle' => "Tirage Classique 13x19cm avec cartonnage",
		'format' => '13x19',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 6,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '20x30',
		'libelle' => "Tirage Classique 20x30cm",
		'format' => '20x30',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 12,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '20x30-c',
		'libelle' => "Tirage Classique 20x30cm avec cartonnage",
		'format' => '20x30',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 15,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '30x45',
		'libelle' => "Tirage Classique 30x45cm",
		'format' => '30x45',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 27,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '15x21',
		'libelle' => "Tirage Classique 15x21cm",
		'format' => '15x21',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 6,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '15x21-c',
		'libelle' => "Tirage Classique 15x21cm avec cartonnage",
		'format' => '15x21',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 8,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '15x15',
		'libelle' => "Tirage Classique 15x15cm",
		'format' => '15x15',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 5,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '20x20',
		'libelle' => "Tirage Classique 20x20cm",
		'format' => '20x20',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 8,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '30x30',
		'libelle' => "Tirage Classique 30x30cm",
		'format' => '30x30',
		'gamme' => 'classique',
		'description' => 'Papier photo prestige',
		'tarif' => 18,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '40x60',
		'libelle' => "Poster 40x60cm sur papier photo premium brillant",
		'format' => '40x60',
		'gamme' => 'poster',
		'description' => 'Papier photo premium brillant',
		'tarif' => 36,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '50x75',
		'libelle' => "Poster 50x75cm sur papier photo premium brillant",
		'format' => '50x75',
		'gamme' => 'poster',
		'description' => 'Papier photo premium brillant',
		'tarif' => 56,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '60x90',
		'libelle' => "Poster 60x90cm sur papier photo premium brillant",
		'format' => '60x90',
		'gamme' => 'poster',
		'description' => 'Papier photo premium brillant',
		'tarif' => 81,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '20x30',
		'libelle' => "Tirage 'Fine Art' 20x30cm",
		'format' => '20x30',
		'gamme' => 'art',
		'description' => "Impression haute qualité sur papier d'art",
		'tarif' => 35,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '30x45',
		'libelle' => "Tirage 'Fine Art' 30x45cm",
		'format' => '30x45',
		'gamme' => 'art',
		'description' => "Impression haute qualité sur papier d'art",
		'tarif' => 60,
		'delai' => 2,
	),
	array(
		'id' => $i++,
		'code' => '40x60',
		'libelle' => "Tirage 'Fine Art' 40x60cm",
		'format' => '40x60',
		'gamme' => 'art',
		'description' => "Impression haute qualité sur papier d'art",
		'tarif' => 85,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '50x75',
		'libelle' => "Tirage 'Fine Art' 50x75cm",
		'format' => '50x75',
		'gamme' => 'art',
		'description' => "Impression haute qualité sur papier d'art",
		'tarif' => 115,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '60x90',
		'libelle' => "Tirage 'Fine Art' 60x90cm",
		'format' => '60x90',
		'gamme' => 'art',
		'description' => "Impression haute qualité sur papier d'art",
		'tarif' => 135,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '20x30',
		'libelle' => "Photographie sur toile 20x30cm",
		'format' => '20x30',
		'gamme' => 'toile',
		'description' => "Impression haute qualité sur toile",
		'tarif' => 80,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '30x45',
		'libelle' => "Photographie sur toile 30x45cm",
		'format' => '30x45',
		'gamme' => 'toile',
		'description' => "Impression haute qualité sur toile",
		'tarif' => 120,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '40x60',
		'libelle' => "Photographie sur toile 40x60cm",
		'format' => '40x60',
		'gamme' => 'toile',
		'description' => "Impression haute qualité sur toile",
		'tarif' => 150,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '60x90',
		'libelle' => "Photographie sur toile 60x90cm",
		'format' => '60x90',
		'gamme' => 'toile',
		'description' => "Impression haute qualité sur toile",
		'tarif' => 210,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '20x30',
		'libelle' => "Photographie contrecollée sur 'Dibond' 20x30cm",
		'format' => '20x30',
		'gamme' => 'dibond',
		'description' => "Impression haute qualité contrecollée sur 'Dibond'",
		'tarif' => 100,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '30x45',
		'libelle' => "Photographie contrecollée sur 'Dibond' 30x45cm",
		'format' => '30x45',
		'gamme' => 'dibond',
		'description' => "Impression haute qualité contrecollée sur 'Dibond'",
		'tarif' => 150,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '40x60',
		'libelle' => "Photographie contrecollée sur 'Dibond' 40x60cm",
		'format' => '40x60',
		'gamme' => 'dibond',
		'description' => "Impression haute qualité contrecollée sur 'Dibond'",
		'tarif' => 180,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '60x90',
		'libelle' => "Photographie contrecollée sur 'Dibond' 60x90cm",
		'format' => '60x90',
		'gamme' => 'dibond',
		'description' => "Impression haute qualité contrecollée sur 'Dibond'",
		'tarif' => 270,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '20x30',
		'libelle' => "Photographie avec encadrement 20x30cm",
		'format' => '20x30',
		'gamme' => 'encadrement',
		'description' => "Impression haute qualité avec encadrement 'Caisse Américaine'",
		'tarif' => 150,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '30x45',
		'libelle' => "Photographie avec encadrement 30x45cm",
		'format' => '30x45',
		'gamme' => 'encadrement',
		'description' => "Impression haute qualité avec encadrement 'Caisse Américaine'",
		'tarif' => 230,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '40x60',
		'libelle' => "Photographie avec encadrement 40x60cm",
		'format' => '40x60',
		'gamme' => 'encadrement',
		'description' => "Impression haute qualité avec encadrement 'Caisse Américaine'",
		'tarif' => 270,
		'delai' => 14,
	),
	array(
		'id' => $i++,
		'code' => '60x90',
		'libelle' => "Photographie avec encadrement 60x90cm",
		'format' => '60x90',
		'gamme' => 'encadrement',
		'description' => "Impression haute qualité avec encadrement 'Caisse Américaine'",
		'tarif' => 400,
		'delai' => 14,
	),
);

$produits = array(
	'gammes' => $gammes,
	'formats' => $formats,
	'delais' => $delais,
	'tirages' => $tirages,
);


?>